theme: minima
title: Fruzsina's portfolio
author: Fruzsina Bodnar
email: fruzsinabodnar0322@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On this page you can get to know me through the projects I have been working on.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
